language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
# command to install dependencies
install: "pip install -r requirements.txt && pip install -r requirements-test.txt && pip install ."
# command to run tests
script: "py.test"
